In [65]:
# !pip install --upgrade sklearn
import pandas as pd
import numpy as np
# !pwd

Requirement already up-to-date: sklearn in /Users/admin/miniconda3/lib/python3.8/site-packages (0.0)
Requirement already satisfied, skipping upgrade: scikit-learn in /Users/admin/miniconda3/lib/python3.8/site-packages (from sklearn) (0.23.2)
Requirement already satisfied, skipping upgrade: scipy>=0.19.1 in /Users/admin/miniconda3/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.5.4)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /Users/admin/miniconda3/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.19.5)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /Users/admin/miniconda3/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.0.1)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in /Users/admin/miniconda3/lib/python3.8/site-packages (from scikit-learn->sklearn) (2.1.0)

In [61]:
df = pd.read_pickle("forecasting/notebooks_exploration_2/['AAPL']_daily.pkl")
# df.dropna(axis=0, inplace=True)
# df = df.reset_index().drop(labels=[i for i in range(10)])
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(axis=1, inplace=True)
display(df,df.info(), df.describe())
# display(df.AAPL)

<class 'pandas.core.frame.DataFrame'>
Index: 5028 entries, 2001-04-02 to 2021-03-26
Columns: 184 entries, ('AAPL', 'open') to ('AAPL', 'year_sin')
dtypes: float64(183), int64(1)
memory usage: 7.1+ MB

              AAPL                                                   \
              open    high      low   close     volume open_10_mean
2001-04-02   22.09   22.66   21.400   21.59    6087700      22.0900
2001-04-03   21.36   21.40   20.130   20.24    6583700      21.7250
2001-04-04   19.76   20.25   18.750   19.50   12240800      21.0700
2001-04-05   20.60   22.50   20.000   20.87    7977900      20.9525
2001-04-06   20.80   21.04   19.900   20.59    5801600      20.9220
...            ...     ...      ...     ...        ...          ...
2021-03-22  120.33  123.87  120.260  123.39  111912284     121.7930
2021-03-23  123.33  124.24  122.140  122.54   95467142     122.2230
2021-03-24  122.82  122.90  120.065  120.09   88530485     122.3360
2021-03-25  119.54  121.66  119.000  120.59   98844681     122.0360
2021-03-26  120.35  121.48  118.920  121.21   94071234     122.0310

                                                                               \
           open_10_median open_10_quantile_5 open_10_quantile_95 open_10_high
2001-04-02         22.090            22.0900             22.0900        22.09
2001-04-03         21.725            21.3965             22.0535        22.09
2001-04-04         21.360            19.9200             22.0170        22.09
2001-04-05         20.980            19.8860             21.9805        22.09
2001-04-06         20.800            19.9280             21.9440        22.09
...                   ...                ...                 ...          ...
2021-03-22        121.550           119.4215            124.9575       125.70
2021-03-23        122.115           120.0935            124.9575       125.70
2021-03-24        122.680           120.0935            124.9575       125.70
2021-03-25        122.115           119.7020            124.9575       125.70
2021-03-26        122.115           119.7020            124.9575       125.70

            ...                                          \
            ... volume_365_median volume_365_quantile_5
2001-04-02  ...         6087700.0             6087700.0
2001-04-03  ...         6335700.0             6112500.0
2001-04-04  ...         6583700.0             6137300.0
2001-04-05  ...         7280800.0             6162100.0
2001-04-06  ...         6583700.0             5858820.0
...         ...               ...                   ...
2021-03-22  ...        49897096.0            20293873.2
2021-03-23  ...        50036513.0            20462095.0
2021-03-24  ...        50155639.0            20462095.0
2021-03-25  ...        50415613.0            20462095.0
2021-03-26  ...        50455071.0            20462095.0

                                                                  \
           volume_365_quantile_95 volume_365_high volume_365_low
2001-04-02              6087700.0       6087700.0      6087700.0
2001-04-03              6558900.0       6583700.0      6087700.0
2001-04-04             11675090.0      12240800.0      6087700.0
2001-04-05             11601365.0      12240800.0      6087700.0
2001-04-06             11388220.0      12240800.0      5801600.0
...                           ...             ...            ...
2021-03-22            177407140.6     332607163.0     11654363.0
2021-03-23            177407140.6     332607163.0     11654363.0
2021-03-24            177407140.6     332607163.0     11654363.0
2021-03-25            177407140.6     332607163.0     11654363.0
2021-03-26            177407140.6     332607163.0     11654363.0


           volume_365_spread week_cos      week_sin  year_cos  year_sin
2001-04-02               0.0      1.0  0.000000e+00 -0.012910  0.999917
2001-04-03          496000.0      0.5  8.660254e-01 -0.030120  0.999546
2001-04-04         6153100.0     -0.5  8.660254e-01 -0.047321  0.998880
2001-04-05         6153100.0     -1.0  1.224647e-16 -0.064508  0.997917
2001-04-06         6439200.0     -0.5 -8.660254e-01 -0.081676  0.996659
...                      ...      ...           ...       ...       ...
2021-03-22       320952800.0      1.0  0.000000e+00  0.175531  0.984474
2021-03-23       320952800.0      0.5  8.660254e-01  0.158559  0.987349
2021-03-24       320952800.0     -0.5  8.660254e-01  0.141540  0.989932
2021-03-25       320952800.0     -1.0  1.224647e-16  0.124479  0.992222
2021-03-26       320952800.0     -0.5 -8.660254e-01  0.107381  0.994218

[5028 rows x 184 columns]

None

              AAPL                                                       \
              open         high          low        close        volume
count  5028.000000  5028.000000  5028.000000  5028.000000  5.028000e+03
mean    183.123661   185.065844   181.022111   183.107105  2.791970e+07
std     160.885537   162.250575   159.308272   160.814157  2.571252e+07
min      12.990000    13.190000    12.720000    13.120000  7.025000e+05
25%      68.680000    69.615000    67.395000    68.425000  1.213032e+07
50%     128.885000   130.495000   127.375000   128.840000  2.223130e+07
75%     240.520000   243.112500   237.130000   240.677500  3.463218e+07
max     702.410000   705.070000   699.570000   702.100000  3.326072e+08

                                                                          \
      open_10_mean open_10_median open_10_quantile_5 open_10_quantile_95
count  5028.000000    5028.000000        5028.000000         5028.000000
mean    183.034107     183.086287         176.635230          189.291610
std     160.389918     160.828170         155.532171          165.889702
min      13.379000      13.470000          13.053000           13.656000
25%      68.188750      68.303750          65.154062           71.949250
50%     128.908250     128.703750         125.143500          132.880000
75%     245.040808     244.060000         231.806000          252.624000
max     691.224500     694.557500         672.623500          701.442500

                    ...                                          \
      open_10_high  ... volume_365_median volume_365_quantile_5
count  5028.000000  ...      5.028000e+03          5.028000e+03
mean    190.148090  ...      2.159035e+07          1.174158e+07
std     166.630862  ...      1.193430e+07          6.881436e+06
min      13.710000  ...      4.244600e+06          2.452040e+06
25%      72.140000  ...      1.265280e+07          7.151240e+06
50%     133.390700  ...      2.125240e+07          1.054034e+07
75%     252.840000  ...      2.928270e+07          1.693766e+07
max     702.410000  ...      5.045507e+07          3.030853e+07

                                                                               \
      volume_365_quantile_95 volume_365_high volume_365_low volume_365_spread
count           5.028000e+03    5.028000e+03   5.028000e+03      5.028000e+03
mean            4.893234e+07    9.769887e+07   7.262936e+06      9.043593e+07
std             2.945448e+07    5.999031e+07   4.202231e+06      5.773998e+07
min             6.087700e+06    6.087700e+06   7.025000e+05      0.000000e+00
25%             3.172030e+07    5.379000e+07   4.391600e+06      4.751310e+07
50%             5.078362e+07    9.624675e+07   6.299400e+06      8.488470e+07
75%             6.404314e+07    1.196178e+08   1.136204e+07      1.078751e+08
max             1.774071e+08    3.326072e+08   1.540660e+07      3.212451e+08


          week_cos      week_sin     year_cos      year_sin
count  5028.000000  5.028000e+03  5028.000000  5.028000e+03
mean     -0.113365  1.815415e-01    -0.007244 -3.399020e-03
std       0.727748  6.517395e-01     0.703865  7.104289e-01
min      -1.000000 -8.660254e-01    -0.999963 -9.999907e-01
25%      -0.500000  0.000000e+00    -0.708627 -7.176769e-01
50%      -0.500000  1.224647e-16    -0.012910  6.432491e-16
75%       0.500000  8.660254e-01     0.690173  7.116566e-01
max       1.000000  8.660254e-01     1.000000  9.999907e-01

[8 rows x 184 columns]